---
#  - hosts: all
#    roles:
#      - base

  - hosts: gitlab
    vars:
      gitlab_external_url: "http://10.23.13.14/"
      gitlab_redirect_http_to_https: 'false'
      gitlab_nginx_listen_https: 'false'
#      gitlab_nginx_listen_port: 8080
      gitlab_nginx_listen_addresses: 
        - "0.0.0.0"
    roles:
      - gitlab
    tasks:
      - name: Restart Gitlab
        shell: "gitlab-ctl restart"

 # - hosts: ec2_tag_Type_formation
 #   roles:
 #     - ose_install



  #  - hosts: all
  #  
  #      roles:
  #          -docker
  #          -dataloop

  #  - hosts: ec2_tag_Type_formation

  #      roles:
  #          -formation

  #  - hosts: ec2_tag_Type_master

  #      roles:
  #          -hassomeotherrole
