---
-   name: Testing for Dataloop image
    shell: docker ps | grep dataloop
    register: dlcontainer
    ignore_errors: True
    changed_when: "dlcontainer.rc != 0"
-   name: Ensure Docker container installed for monitoring
    shell: docker run -d -e API_KEY=d2fc7190-7176-4415-b498-814e52423823 --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --privileged dataloop/dataloop-docker:centos7
    when: dlcontainer.rc == 1
-   name: Ensure Cron jobs to tidy images
    cron: name="remove dangling images from docker" minute="0" hour="*" user="root" job='docker rmi $(docker images -f "dangling=true" -qa)'
