---
- name: Set PV
  lvg:
    vg: vg_oscp
    pvs: "{{yumserver_pv_disk}}"
    pesize: 32

- name: Set up LV
  lvol: vg=vg_oscp lv=yumserver size={{ yumserver_lv_size }}

- name: Format attached disk
  filesystem: fstype=xfs dev=/dev/mapper/vg_oscp-yumserver

- name: Mount volume
  mount: name={{ yumserver_data_dir }} src=/dev/mapper/vg_oscp-yumserver fstype=xfs opts=noatime state=mounted

- name: Install Createrepo .
  package: name=createrepo state=installed

- name: Build the Yum repo index
  command: "createrepo {{ yumserver_data_dir }} "

- name: Install Apache
  package: name=httpd state=installed

- name: Create symnolic link to repo directory
  file:
   src: '{{ yumserver_data_dir }}'
   dest:  '/var/www/html/temenos' 
   state: link
  notify:
    - Restart Apache

- name: Add iptables rule
  iptables:
   chain: INPUT
   action: append
   source: 10.0.0.0/24
   destination: 80

- name:  FirewallD Enable
  firewalld: immediate=true service=http permanent=true state=enabled

- name: Install SElinux python policy utils
  package: name=policycoreutils-python state=installed

- name: Enable SELinux to allow HTTP Access
  command: "{{ item }}"
  with_items: 
    - semanage fcontext -a -t public_content_rw_t '{{yumserver_data_dir }}(/.*)?'
    - restorecon -R {{ yumserver_data_dir }}
