---

plugins_list:
    - bouncycastle-api
    - credentials
    - momentjs
    - ssh-credentials
    - durable-task
    - structs
    - workflow-step-api
    - pipeline-stage-view
    - workflow-scm-step
    - docker-commons
    - git-client
    - script-security
    - junit
    - git-server
    - matrix-project
    - display-url-api
    - mailer
    - git
    - ansicolor
    - cloudbees-folder
    - windows-slaves
    - docker-workflow
    - icon-shim
    - matrix-auth
    - antisamy-markup-formatter
    - workflow-support
    - build-with-parameters
    - branch-api
    - token-macro
    - Parameterized-Remote-Trigger
    - workflow-cps-global-lib
    - build-flow-plugin
    - pam-auth
    - ldap
    - pipeline-milestone-step
    - external-monitor-job
    - javadoc
    - ant
    - run-condition
    - scm-api
    - maven-plugin
    - pipeline-rest-api
    - conditional-buildstep
    - parameterized-trigger
    - envfile
    - workflow-api
    - jquery-detached
    - ace-editor
    - workflow-cps
    - pipeline-stage-step
    - pipeline-build-step
    - pipeline-input-step
    - workflow-job
    - handlebars
    - pipeline-graph-analysis
    - workflow-durable-task-step
    - plain-credentials
    - credentials-binding
    - pipeline-model-api
    - workflow-basic-steps
    - pipeline-stage-tags-metadata
    - authentication-tokens
    - pipeline-model-declarative-agent
    - workflow-multibranch
    - pipeline-model-definition
    - workflow-aggregator